package com.DonutAddon.addon.modules.AI;

public enum MiningState {
    IDLE,
    CENTERING,
    SCANNING_PRIMARY,
    MINING_PRIMARY,
    HAZARD_DETECTED,
    CALCULATING_DETOUR,
    FOLLOWING_DETOUR,
    CHANGING_DIRECTION,
    ROTATING,
    RTP_INITIATED,
    RTP_WAITING,
    RTP_COOLDOWN,
    RTP_SCANNING_GROUND,
    SEARCHING_SAFE_MINEDOWN,  // NEW STATE
    MOVING_TO_MINEDOWN,        // NEW STATE
    MINING_DOWN,
    STOPPED
}
